package cc.zorcc.tenet.serde;

import java.lang.annotation.*;

/// Mark a class that was generated by annotation processor, or manually override, aiming at a target class
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Inherited
@Documented
public @interface AimAt {
    /**
     *   The target class that was generated from
     */
    String target();
}
