package cn.zorcc.common.network;

public interface Handler {

    /**
     *   After channel got connected, this function would be invoked
     */
    void onConnected(Channel channel);

    /**
     *   After data has been received, this function would be invoked in reader thread, business logic should be put here
     *   Note that the data object was generated by channel's decoder, if decoder's decode() return null then this function won't be invoked
     *   If FrameworkException was thrown inside this function, the channel would be immediately shutdown to guard the application
     */
    void onRecv(Channel channel, Object data);

    /**
     *   Before channel got shutdown, this function would be invoked
     *   Note that some goodbye message could be sent in this function to perform a graceful shutdown
     */
    void onShutdown(Channel channel);

    /**
     *   After connection was closed, this function would be invoked
     *   Note that you can't expect sending some data in this function, since the connection has already been closed
     */
    void onRemoved(Channel channel);
}
