package cn.zorcc.common.database;

import java.lang.annotation.*;

@Target({ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Id {
    /**
     *   Whether the table 'id' column was auto generated by the database
     */
    boolean auto() default true;

    /**
     *   Column value
     */
    String value() default "id";

    /**
     *   Column ordinal
     */
    int ordinal() default 0;
}
