package cn.zorcc.common.network.api;

import cn.zorcc.common.network.Channel;
import cn.zorcc.common.network.TaggedResult;

/**
 *   Handler represents the actual business logic that a channel should perform in Protocol phase
 */
public interface Handler {
    /**
     *   After channel got connected, this function would be invoked
     *   The definition of connected means the Sentry has been upgraded to Protocol
     *   If a RuntimeException was thrown in this function, the channel would be immediately closed to guard the application
     */
    void onConnected(Channel channel);

    /**
     *   After data were received, this function would be invoked in poller thread, business logic should be put here
     *   Note that the data object was generated by channel's decoder, if decode() return null then this function won't be invoked
     *   If a RuntimeException was thrown in this function, the channel would be immediately closed to guard the application
     */
    TaggedResult onRecv(Channel channel, Object data);

    /**
     *   Before channel was going to shut down, this function would be invoked in caller thread
     *   For most use cases, this function is used to send some goodbye message to perform a graceful shutdown
     *   If a RuntimeException was thrown in this function, the channel would be immediately closed to guard the application
     */
    void onShutdown(Channel channel);

    /**
     *   After connection was closed, this function would be invoked
     *   Note that you can't expect sending some data in this function, since the connection has already been closed
     *   If connection failed in Sentry phase, this function would never be triggered (if there's an onConnected(), there is an onRemoved(), vice versa)
     */
    void onRemoved(Channel channel);
}
